# Generated by Django 4.2.7 on 2023-11-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ImageField(upload_to='portfolio/')),
                ('phone', models.URLField()),
                ('address', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=40),
        ),
    ]
