# Generated by Django 4.2.7 on 2023-11-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact_alter_about_career'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
