# Generated by Django 4.2.7 on 2023-11-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
